# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'tictactoe', '0002_game_third_player'), (b'tictactoe', '0003_auto_20170107_2124'), (b'tictactoe', '0004_auto_20170107_2125')]

    dependencies = [
        ('tictactoe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='third_player',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='games_third_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
