# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_game_third_player_squashed_0004_auto_20170107_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='third_player',
        ),
    ]
